name: hw6

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          os: [ubuntu-22.04]

        fail-fast: false

    steps:

    - uses: actions/checkout@v3

    - name: Install dependency
      run: |
        sudo apt-get -q update
        sudo apt-get -qy install \
            curl build-essential make cmake libc6-dev \
            gcc g++ gfortran intel-mkl-full \
            python3 python3-pip python3-pytest \
            python3-numpy python3-scipy python3-pandas python3-matplotlib \
            jupyter
        cd /usr/bin ; sudo ln -sf py.test-3 py.test

    - name: Configure CMake
      run: |
        run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        
    - name: Build CMake
      run: |
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        
    - name: Test
      run: |
        run: python3 -m pytest
