name: Ford_Fulkerson

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          os: [ubuntu-22.04]

        fail-fast: false

    steps:

    - uses: actions/checkout@v3

    - name: Install dependency
      run: |    
        sudo apt-get update
        sudo apt install -qy make
        sudo apt install -qy cmake
        sudo apt install -qy python3 
        sudo apt install -qy python3-pip  
        pip3 install pybind11
        pip3 install pybind11-global 
        pip3 install pytest
        pip3 install numpy
        pip3 install networkx
        pip3 install notebook
        pip3 install matplotlib

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build
        
    - name: Build CMake
      run: |
        cmake --build ${{github.workspace}}/build
        
    - name: Test
      run: |
        python3 -m pytest
